version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/random_forest_model:/app/random_forest_model
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    container_name: frontend